token: "" #Discord Bot token https://discord.com/developers/applications
activity: "©Gaway-code" #Widoczna aktyność bota
json: "false" #Pobieranie danych z mysql z tabeli memki kolumna link (jeżeli wyłaczone to pobiera dane z folderu memiki)
json-url: "http://meme.gaway.pl/json.php" #Url do jsona wygenerowanego z aplikacji (Discord-meme-bot-Panel)
admintag: "Gaway#4391" #Nick uprawniony do aktualizacji memów (z plików) i do usuwania wiadomości
memetitle: "Codzienna dawka memów" #Tytuł przy wysyłaniu mema
updatemessage: "Zaktualizowane liste memów" #wiadomość jaka wyswietla się po wykonaniu komendy aktualizującej memy
permissionmessage: "Nie masz uprawnień" #Wiadomosc wysyłana do osoby bez uprawnień
memecommand: "!meme" #komenda do wysłania mema
updatecommand: "!update" #komenda do aktualizacji mema
reloadcommand: "!reload" #komenda do przeładowania konfiguracji
deletecommand: "!usun" #komenda do usuwania wiadomosci
